import { Inter } from 'next/font/google'
import './globals.css'
import navbar from "./components/navbar";


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Lab linux',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const Navbar = navbar

  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
 
      </body>
    </html>
  )
}
